### ISSUE TITLE
Latest Version Update

### ISSUE THREAD

**Issue by Weurzburger** [victronenergy/apps_vrm_android#2]
Hey Victron Team,

I really like your work here at Github. It´s nice to have a community and a support like this.
But is it possible to update the code here of the VRM adroit app to the current version?

**Comment by thlassche** [comment]
Hey @Weurzburger any particular problems you run into?

**Comment by Weurzburger** [comment]
Good morning,
no particular problem. Just would like deep into the app the next days. So it would be nice to have it up to date.

**Comment by thlassche** [comment]
@Weurzburger Ah, in that case it makes sense. This app is not actively used anymore. The current app is a PWA powered by VRM: https://vrm.victronenergy.com/installation-overview
